from django.urls import path

from . import views


app_name = 'cashflow'

urlpatterns = [
    path(
        '',
        views.RecordListView.as_view(),
        name='index'
    ),
    path(
        'ajax/load-categories/',
        views.load_categories,
        name='ajax_load_categories'
    ),
    path(
        'ajax/load-subcategories/',
        views.load_subcategories,
        name='ajax_load_subcategories'
    ),
    path(
        'record/create/',
        views.RecordCreateView.as_view(),
        name='create_record'
    ),
    path(
        'record/<int:record_id>/',
        views.RecordDetailView.as_view(),
        name='record_detail'
    ),
    path(
        'record/<int:record_id>/edit/',
        views.RecordUpdateView.as_view(),
        name='edit_record'
    ),
    path(
        'record/<int:record_id>/delete/',
        views.RecordDeleteView.as_view(),
        name='delete_record'
    ),
    path(
        'status/',
        views.StatusListView.as_view(),
        name='status'
    ),
    path(
        'status/<int:status_id>/',
        views.StatusDetailView.as_view(),
        name='status_detail'
    ),
    path(
        'status/create/',
        views.StatusCreateView.as_view(),
        name='create_status'
    ),
    path(
        'status/<int:status_id>/edit/',
        views.StatusUpdateView.as_view(),
        name='edit_status'
    ),
    path(
        'status/<int:status_id>/delete/',
        views.StatusDeleteView.as_view(),
        name='delete_status'
    ),
    path(
        'type/',
        views.TypeListView.as_view(),
        name='type'
    ),
    path(
        'type/create/',
        views.TypeCreateView.as_view(),
        name='create_type'
    ),
    path(
        'type/<int:type_id>/edit/',
        views.TypeUpdateView.as_view(),
        name='edit_type'
    ),
    path(
        'type/<int:type_id>/delete/',
        views.TypeDeleteView.as_view(),
        name='delete_type'
    ),
    path(
        'type/<int:type_id>/',
        views.TypeDetailCategoryListView.as_view(),
        name='type_detail'
    ),
    path(
        'type/<int:type_id>/category/create/',
        views.CategoryCreateView.as_view(),
        name='create_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/edit/',
        views.CategoryUpdateView.as_view(),
        name='edit_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/delete/',
        views.CategoryDeleteView.as_view(),
        name='delete_category'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/',
        views.CategoryDetailSubcategoryListView.as_view(),
        name='category_detail'
    ),
    path(
        'type/<int:type_id>/category/<slug:category_slug>/subcategory/create/',
        views.SubcategoryCreateView.as_view(),
        name='create_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>/edit/'
        ),
        views.SubcategoryUpdateView.as_view(),
        name='edit_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>/delete/'
        ),
        views.SubcategoryDeleteView.as_view(),
        name='delete_subcategory'
    ),
    path(
        (
            'type/<int:type_id>/category/<slug:category_slug>/'
            'subcategory/<slug:sub_slug>'
        ),
        views.SubcategoryDetailView.as_view(),
        name='subcategory_detail'
    ),
]
