# Generated by Django 3.2.16 on 2025-03-06 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=1, help_text='Автор записи', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='auth.user', verbose_name='Автор записи'),
            preserve_default=False,
        ),
    ]
