# Generated by Django 3.2.16 on 2025-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_auto_20250306_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='typemoney',
            name='category',
            field=models.ManyToManyField(related_name='category', to='cashflow.Category'),
        ),
    ]
