# Generated by Django 3.2.16 on 2025-03-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_auto_20250307_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(help_text='статус записи', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.statusmoney', verbose_name='Статус'),
        ),
    ]
