# Generated by Django 3.2.16 on 2025-03-08 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0009_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, help_text='Автор категории', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auth.user', verbose_name='Автор категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusmoney',
            name='user',
            field=models.ForeignKey(default=1, help_text='Автор статуса', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='auth.user', verbose_name='Автор статуса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(default=1, help_text='Автор подкатегории', on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='auth.user', verbose_name='Автор подкатегории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typemoney',
            name='user',
            field=models.ForeignKey(default=1, help_text='Автор Типа', on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auth.user', verbose_name='Автор Типа'),
            preserve_default=False,
        ),
    ]
