# Generated by Django 3.2.16 on 2025-03-08 05:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0010_auto_20250308_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMoney',
            new_name='Type',
        ),
    ]
