# Generated by Django 3.2.16 on 2025-03-08 05:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0011_rename_typemoney_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusMoney',
            new_name='Status',
        ),
    ]
