# Generated by Django 3.2.16 on 2025-03-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0012_rename_statusmoney_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(blank=True, help_text='статус записи', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.status', verbose_name='Статус'),
        ),
    ]
