# Generated by Django 3.2.16 on 2025-03-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0013_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(help_text='Подкатегория записи', null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.subcategory', verbose_name='Подкатегория'),
        ),
    ]
