# Generated by Django 3.2.16 on 2025-03-08 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0015_alter_status_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи', verbose_name='Дата и время создания'),
        ),
    ]
